Repository Azure/CloudShell, pull requests merged in 2022-06, with the labels that each got.

#201 Use new Hashicorp Releases API
  linux/tools.Dockerfile
Labels: Area-image

#152 Install GC module as opposed to Az GC module
  linux/powershell/Dockerfile.Data.json
  linux/powershell/Invoke-PreparePowerShell.ps1
  linux/powershell/setupPowerShell.ps1
  tests/PSinLinuxCloudShellImage.Tests.ps1
Labels: Area-image, Iteration-Current, Status-In_review

#209 Added escape characters thus preventing the creation of file =0.2.2 in /opt
  linux/base.Dockerfile
  linux/installMaven.sh
Labels: Area-image, Iteration-Current, Status-In_review, Tool_upgrade
